var cardList = {
	'Advokatbyrå': {	'text': ''},
	'Apotek': {			'text': ''},
	'Arbetsförm.': {	'text': 'Arbetsförmedling.'},
	'Arkelogiskt': {	'text': 'Utgrävningen av guldgubbar i Vång tex.'},
	'Attraktioner': {	'text': 'Alla sorters ställen som är intressanta för turister.'},
	'Auktion': {		'text': ''},
	'Bankomat': {		'text': ''},
	'Bar': {			'text': ''},
	'Bastu/Spa': {		'text': ''},
	'Bensinmack': {		'text': ''},
	'Bergstopp': {		'text': ''},
	'Bibliotek': {		'text': ''},
	'Bilaffär': {		'text': ''},
	'Bilbesikt.': {		'text': 'Bilbesiktning.'},
	'Biltvätt': {		'text': ''},
	'Biluthyrning': {	'text': ''},
	'Biograf': {		'text': ''},
	'Bokhandel': {		'text': ''},
	'Bostadsomr.': {	'text': 'Ett område med mestadels bostäder.'},
	'Bowlinghall': {	'text': ''},
	'Brandstation': {	'text': ''},
	'Busstation': {		'text': ''},
	'Cafe': {			'text': ''},
	'Camping': {		'text': ''},
	'Dataffär': {		'text': ''},
	'Djuraffär': {		'text': ''},
	'Domstol': {		'text': ''},
	'Dykställe': {		'text': 'En plats där sportdykare kan hålla till, ett sjunket skepp tex.'},
	'Fiskeställe': {	'text': ''},
	'Fitness': {		'text': 'Ett ställe där man tränar fitness.'},
	'Flygplats': {		'text': ''},
	'Fort/Slott': {		'text': ''},
	'Frisör': {			'text': ''},
	'Fängelse': {		'text': ''},
	'Färja': {			'text': 'Plats där en färja lägger till.'},
	'Försäkring': {		'text': 'Ett försäkringsbolag.'},
	'Geologiskt': {		'text': 'En geologiskt intressant plats som tex en jättegryta.'},
	'Golfbana': {		'text': ''},
	'Grotta': {			'text': ''},
	'Hembygdsf.': {		'text': 'Hembygdsförening.'},
	'Hotell': {			'text': ''},
	'Industrizon': {	'text': ''},
	'Isrink': {			'text': ''},
	'Kasino': {			'text': ''},
	'Kebab': {			'text': ''},
	'Kemtvätt': {		'text': ''},
	'Klädaffär': {		'text': ''},
	'Klättring': {		'text': 'Ett ställe att klättra på som en bergvägg tex.'},
	'Konsulat': {		'text': 'Konsulat eller ambassad.'},
	'Korvkiosk': {		'text': ''},
	'Kyrka': {			'text': ''},
	'Kyrkogård': {		'text': ''},
	'Köpcenter': {		'text': 'Ett större varuhus.'},
	'Laddstation': {	'text': 'Ett ställe där eldrivna fordon (bilar, cyklar) kan laddas.'},
	'Land': {			'text': 'Sverige, Norge tex.'},
	'Län': {			'text': 'Blekingelän tex.'},
	'Marina': {			'text': ''},
	'Marknadsp.': {		'text': 'Plats där marknader hålls.'},
	'Mataffär': {		'text': ''},
	'Millitär': {		'text': 'Millitär installation, övningsfält tex.'},
	'MiniGolf': {		'text': ''},
	'Minnesmärke': {	'text': 'Monument, staty.'},
	'Motell': {			'text': ''},
	'Museum': {			'text': ''},
	'Mäklare': {		'text': 'Fastighetsmäklare.'},
	'Naturres.': {		'text': 'Naturreservat, nationalpark.'},
	'Nöjespark': {		'text': ''},
	'Optiker': {		'text': ''},
	'Park': {			'text': 'Stadspark tex.'},
	'Parkering': {		'text': ''},
	'Pizzeria': {		'text': ''},
	'Polis': {			'text': ''},
	'Postkontor': {		'text': ''},
	'Rastplats': {		'text': 'Rastplats längs en väg.'},
	'Resebyrå': {		'text': ''},
	'Restaurang': {		'text': ''},
	'Ruiner': {			'text': ''},
	'Simbasäng': {		'text': ''},
	'Sjukhus': {		'text': ''},
	'Skidåkning': {		'text': 'En skidbacke tex.'},
	'Skola': {			'text': ''},
	'Slagfält': {		'text': 'Plats där ett slag har utspelats.'},
	'Snabbköp': {		'text': ''},
	'Spelhall': {		'text': 'Ett ställe med spelmaskiner.'},
	'SportCenter': {	'text': 'Vanligtvis en större byggnad med anläggningar för flera olika sporter.'},
	'Sportaffär': {		'text': ''},
	'Stadium': {		'text': ''},
	'Strand': {			'text': ''},
	'Städer': {			'text': 'Stad, by eller samhälle.'},
	'Tandläkare': {		'text': ''},
	'Taxi': {			'text': 'Plats där taxibilar samlas.'},
	'Teater': {			'text': ''},
	'Telekomb.': {		'text': 'Ett telekombolag , Alltele tex.'},
	'Tennisbana': {		'text': ''},
	'Toalett': {		'text': 'Publik toalett'},
	'Turistinfo': {		'text': 'Turistinformation, tavla eller byrå.'},
	'Tågstation': {		'text': ''},
	'Utsiktspunkt': {	'text': ''},
	'Vattenfall': {		'text': ''},
	'Vattenpark': {		'text': ''},
	'Veterinär': {		'text': ''},
	'Vulkan': {			'text': ''},
	'Växelkontor': {	'text': 'Ställe där man kan växla pengar.'},
	'Vårdcentral': {	'text': ''},
	'Zoo': {			'text': ''},
	'Ålderdomsh.': {	'text': 'Ålderdomshem.'},
	'Återvinning': {	'text': ''},
	'Ö': {				'text': 'En ö i havet eller i en sjö helt enkelt.'}
}